version: '3.2'
services:
  server:
    image: 92840/server:${BUILD_NUMBER}
    networks:
    - webapp
    depends_on: 
    - db
    environment:
    - MONGO_DB_HOSTNAME=db
    - MONGO_DB_USERNAME=mongoadmin
    - MONGO_DB_PASSWORD=secret
    - BRAINTREE_MERCHANT_ID=n74dc2kw9g3ws389
    - BRAINTREE_PUBLIC_KEY=bgytmgzhz5f6t2tg
    - BRAINTREE_PRIVATE_KEY=e6f226166da99d874f00008f0bba14fe
  client:
    image: 92840/client:${BUILD_NUMBER}
    ports:
    - 3000:3000
    networks:
    - webapp
    depends_on:
    - db
    - server
    hostname: server
  db:
    image: mongo
    ports:
    - 8000:8000
    networks:
    - webapp
    volumes:
    - webapp:/data/db
    environment:
    - MONGO_INITDB_ROOT_USERNAME=mongoadmin
    - MONGO_INITDB_ROOT_PASSWORD=secret
    - BRAINTREE_MERCHANT_ID=n74dc2kw9g3ws389
    - BRAINTREE_PUBLIC_KEY=bgytmgzhz5f6t2tg
    - BRAINTREE_PRIVATE_KEY=e6f226166da99d874f00008f0bba14fe
volumes:
  webapp:
    driver: local
networks:
  webapp:
    driver: bridge
  